module.exports.workplaceList = ['Mandalay General Hospital','Palace Hospital Mandalay','Asia Royal Hospital Yangon','Sakura Hospital Yangon']

module.exports.studentYearList = ['First MBBS','Second MBBS','Third MBBS','Final Part One','Final Part Two','Graduated']

module.exports.interestedFieldList = ['Anatomy','Physiology','Biochemistry']

module.exports.accountTypeList = ['doctor', 'medical student', 'other heathcare professional', 'student of other heathcare professional']

module.exports.genderList = ['male', 'female', 'other']

module.exports.universityList = [
	"University of Medicine-1, Yangon",
	"University of Medicine-2, Yangon",
	"University of Medicine, Mandalay",
	"University of Medicine, Magway",
	"University of Medicine, Taunggyi",
	"Defence Services Medical Academy, Mingaladon, Yangon"
]

module.exports.workList = [
	'Physician',
	'Medical Officer',
	'Assistant Surgeon',
	'Professor',
	'Assistant Professor',
	'Surgeon',
	'Pediatrician',
	'Lecturer'
]

module.exports.specialityList = [
	'Allergy and immunology',
	'Adolescent medicine',
	'Anesthesiology',
	'Aerospace medicine',
	'Cardiology',
	'Cardiothoracic surgery',
	'Child and adolescent psychiatry',
	'Clinical neurophysiology',
	'Colorectal surgery',
	'Dermatology',
	'Developmental pediatrics',
	'Emergency medicine',
	'Endocrinology',
	'Family Medicine',
	'Forensic pathology',
	'Forensic psychiatry',
	'Gastroenterology',
	'General surgery',
	'General surgical oncology',
	'Geriatrics',
	'Geriatric psychiatry',
	'Gynecologic oncology',
	'Hematology',
	'Hematologic pathology',
	'Infectious disease',
	'Internal medicine',
	'Interventional radiology',
	'Intensive care medicine',
	'Maternal-fetal medicine',
	'Medical biochemistry',
	'Medical genetics',
	'Medical oncology',
	'Neonatology',
	'Nephrology',
	'Neurology',
	'Neuropathology',
	'Neurosurgery',
	'Nuclear medicine',
	'Obstetrics and gynecology',
	'Occupational medicine',
	'Ophthalmology',
	'Orthopedic surgery',
	'Oral and maxillofacial surgery',
	'Otorhinolaryngology',
	'Palliative care',
	'Pathology',
	'Pediatrics',
	'Pediatric allergy and immunology',
	'Pediatric cardiology',
	'Pediatric emergency medicine',
	'Pediatric endocrinology',
	'Pediatric gastroenterology',
	'Pediatric hematology and oncology',
	'Pediatric infectious disease',
	'Pediatric nephrology',
	'Pediatric respiratory medicine',
	'Pediatric rheumatology',
	'Pediatric surgery',
	'Physical medicine and rehabilitation',
	'Plastic, reconstructive and aesthetic surgery',
	'Psychiatry',
	'Public health',
	'Radiation oncology',
	'Radiology',
	'Reproductive endocrinology and infertility',
	'Respiratory medicine',
	'Rheumatology',
	'Sports medicine',
	'Thoracic surgery',
	'Neuroradiology',
	'Urology',
	'Vascular surgery']

module.exports.countryList =  [
	"Afghanistan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas (the)",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia (Plurinational State of)",
	"Bonaire, Sint Eustatius and Saba",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"Brazil",
	"British Indian Ocean Territory (the)",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cayman Islands (the)",
	"Central African Republic (the)",
	"Chad",
	"Chile",
	"China",
	"Christmas Island",
	"Cocos (Keeling) Islands (the)",
	"Colombia",
	"Comoros (the)",
	"Congo (the Democratic Republic of the)",
	"Congo (the)",
	"Cook Islands (the)",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Curaçao",
	"Cyprus",
	"Czechia",
	"Côte d'Ivoire",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic (the)",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Falkland Islands (the) [Malvinas]",
	"Faroe Islands (the)",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories (the)",
	"Gabon",
	"Gambia (the)",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See (the)",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran (Islamic Republic of)",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea (the Democratic People's Republic of)",
	"Korea (the Republic of)",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic (the)",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands (the)",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia (Federated States of)",
	"Moldova (the Republic of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands (the)",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger (the)",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands (the)",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine, State of",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines (the)",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Republic of North Macedonia",
	"Romania",
	"Russian Federation (the)",
	"Rwanda",
	"Réunion",
	"Saint Barthélemy",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Martin (French part)",
	"Saint Pierre and Miquelon",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Sint Maarten (Dutch part)",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia and the South Sandwich Islands",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan (the)",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Taiwan (Province of China)",
	"Tajikistan",
	"Tanzania, United Republic of",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands (the)",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates (the)",
	"United Kingdom of Great Britain and Northern Ireland (the)",
	"United States Minor Outlying Islands (the)",
	"United States of America (the)",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela (Bolivarian Republic of)",
	"Viet Nam",
	"Virgin Islands (British)",
	"Virgin Islands (U.S.)",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Åland Islands"
];